version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: abeloborodova/stripe_pay:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
